### ISSUE TITLE
milestone2 to-do list - preprocessing

### ISSUE THREAD

**Issue by Kingslin0810** [UBC-MDS/DSCI_522_Group19_Wine_Quality_Score_Predictor#16]
preprocessing (pre-work prior to model fit) (Zack/Pavel)
    - incl. column transformer

**Comment by zackt113** [comment]
Hi Pavel. I will push my codes for preprocessing by the end of tonight, please find it under src folder.  How about I am working on the python script for the preprocessing part, and I will finish the code for model fitting tomorrow. And you can check that code as well and work on the python script for the model fitting? Because I recognized that it may be too much works for you if you are doing both scripts.

**Comment by plevchen** [comment]
Sounds good

**Comment by Kingslin0810** [comment]
Heads-up - (I am not fully knowing how to use this)  - on a high level we can use library(feather) to read the "data table" that's generated by our python scripts (e.g. preprocessing output) to be showed up through the code chunk of RStudio. Reference:
- https://www.rstudio.com/blog/feather/
- https://github.com/wesm/feather

**Comment by plevchen** [comment]
Working with feather files is not difficult, but in our case not much value is added. Feather files make sense for huge databases with millions of rows to save space and make the process of reading and writing data much faster. In our case we could use regular .csv files without noticing any issues. Thus, I think we should just proceed with a simple case of using .csv files as we were doing in 571 and 573

**Comment by plevchen** [comment]
> Hi Pavel. I will push my codes for preprocessing by the end of tonight, please find it under src folder. How about I am working on the python script for the preprocessing part, and I will finish the code for model fitting tomorrow. And you can check that code as well and work on the python script for the model fitting? Because I recognized that it may be too much works for you if you are doing both scripts.

Zack, for some reason I couldn't your preprocessing script in the folder. So, I just created it from scratch and named as 'preprocessing.py'. The script is working 100%, but I didn't bother for the first pass with writing documentation to each function. The plan is to make all required scripts first and then polish documentation inside those scripts

**Comment by zackt113** [comment]
> > Hi Pavel. I will push my codes for preprocessing by the end of tonight, please find it under src folder. How about I am working on the python script for the preprocessing part, and I will finish the code for model fitting tomorrow. And you can check that code as well and work on the python script for the model fitting? Because I recognized that it may be too much works for you if you are doing both scripts.
> 
> Zack, for some reason I couldn't your preprocessing script in the folder. So, I just created it from scratch and named as 'preprocessing.py'. The script is working 100%, but I didn't bother for the first pass with writing documentation to each function. The plan is to make all required scripts first and then polish documentation inside those scripts

Oh, you may be misunderstood my comments before, I was saying that I finished the raw code for preprocessing and I am going to write the script after tomorrow's meeting. Haha but anyways thanks for your work on the script! And I have just pushed my raw code for the model fitting as well. We can discuss further tomorrow! Have a good night!

**Comment by Kingslin0810** [comment]
Heard some feedback from Tiffany today in the class; for preprocess script, I think we only need to combine white/red csv, then split test/train (as opposed to have the transform with pipeline); as our EDA will be based on train data only. 

Then we can move the numerical feature and binary feature pipeline as part of model fit script or separate it to a 2nd preprocess script.  As our EDA analysis will be based on train df rather than preprocessor data. 

Pavel - what do you think?
