### ISSUE TITLE
EDA workflow for wine quality score prediction

### ISSUE THREAD

**Issue by Kingslin0810** [UBC-MDS/DSCI_522_Group19_Wine_Quality_Score_Predictor#3]
Do we agree on this workflow?
1. formulate question - what quality score (from 4 to 7) can we predict for various wines based on features for fixed acidity, volatile acidity, cltric acid, residual sugar, chlorides, free sulfur dioxide, total sulfur dioxide, density, pH, sulphates, alcohol, and red/white wines?
2. read in data from https://archive-beta.ics.uci.edu/ml/datasets/wine+quality
3. what package and dependency do we need?
4. look at the top and bottom of the data
5. check missing values in the data and decide how to handle them
6. validate with at least one external data source
7. make plots to analyze the data distribution
8. try some solution models 
9. follow up questions to re-define statistic questions if needed

**Comment by manju-abhinandana** [comment]
Agreed.
The point 8 can be updated to say:
8. Build model using a baseline model, SVM, Logistic Regression.

**Comment by plevchen** [comment]
I think for EDA we don't need section 8. Instead I would also add overlay of the plots for all numerical variables with two types of wine ("red"/"white")

**Comment by Kingslin0810** [comment]
Will reflect white/red wine types in the numerical feature analysis. Update the workflow as well. Will try running through a few classifier models and update our predictive questions as we go.

**Comment by zackt113** [comment]
Yes, agree with it, will do some modifications later. But overall, we are good to go.

**Comment by manju-abhinandana** [comment]
Got it. Point 8 is not part of EDA. It is part of the Analysis Plan.

**Comment by Kingslin0810** [comment]
Yes, we will build our models based on our initial EDA, and then we can
re-define our predictive questions as needed. Let’s have a brief discussion
of this in the next group meeting.
