### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/DSCI_522_Group19_Wine_Quality_Score_Predictor#61]
**2. Project set-up: Mechanics**

Comments
Where do we contact for contributing?

**3. Project proposal: reasoning**

Comments
Why are you picking some specific features, searching for missing values, scaling some parts, and encoding categorical variables into useable parts? What types of plots? Any hypothesizes?

You write here "Following the `ColumnTransformer` process, we will dive deep into the class imbalance issue we figured out in the EDA process and add class_weight argument in the model." There could be an imbalance in the classes, in which you would have to under-sample or oversample. Which one will you utilize? What packages will you use will you create synthetic?

What about missing data? How will you handle the missing data if there is some? (doesn't matter if there isn't any you should propose a method before EDA)

Have you thought of using wrapper algorithms (boruta algorithm) for feature selection?

Will you do cross-validation?

What about metrics? That was not touched upon in the project proposal.
A suggestion for metrics to determine the performance of your models is Area Under Curve (AUC). The Area Under the Curve (AUC) measures the ability of a classifier to distinguish between classes and is used as a summary of the ROC curve. Also, look into and SHAP (Shapley Additive exPlanations), which explains the direction of each variable compared to the outcome variable.

Spelling errors/grammar errors. "Because if the user of our model, accidentally buy a predicted good wine, but actually it is a poor one, the they may lose a lot of money. "

**5. Exploratory data analysis in a literate code document: VIZ**

Comments
If figure captions are not provided the plot should be clearly explained in the text. I would recommend using figure captions. Missing legends and X and Y axis labels. 

**5. Exploratory data analysis in a literate code document: REASONING**

Comments
"After exploring the data distribution for various quality scores, class imbalance could be an issue which require further considerations. As shown in the above table, a vast majority of the sample wines are normal wine; while only a couple of samples are classified as poor or excellent. We may start our model with over- or under-sampling method to balance each class depends on whether it is a vital problem. " What are you going to utilize to fix this?

**Comment by Kingslin0810** [comment]
> Comments Where do we contact for contributing?

Will reflect the email contact info in the contributing file.

> **3. Project proposal: reasoning**
> 
> Comments Why are you picking some specific features, searching for missing values, scaling some parts, and encoding categorical variables into useable parts? What types of plots? Any hypothesizes?

We are not completely sure of this comment; however, we indeed plan to use Recursive Feature Elimination to drop some features based on feature importances, given our correlation plot indicates some features have low correlation to the target. 

> You write here "Following the `ColumnTransformer` process, we will dive deep into the class imbalance issue we figured out in the EDA process and add class_weight argument in the model." There could be an imbalance in the classes, in which you would have to under-sample or oversample. Which one will you utilize? What packages will you use will you create synthetic?
> 

This is a good comment that we neglect to mention in the proposal; we will add this and modify our model accordingly.  

> What about missing data? How will you handle the missing data if there is some? (doesn't matter if there isn't any you should propose a method before EDA)

As mentioned in our EDA there is no missing data in your raw data. 

> 
> Have you thought of using wrapper algorithms (boruta algorithm) for feature selection?
> 

We decide to use Recursive Feature Elimination for the feature selection, and this will be reflected in our proposal.

> Will you do cross-validation?
> 

Yes we did cross-validation when establishing our model and this will be reflected in the proposal. 

> What about metrics? That was not touched upon in the project proposal. A suggestion for metrics to determine the performance of your models is Area Under Curve (AUC). The Area Under the Curve (AUC) measures the ability of a classifier to distinguish between classes and is used as a summary of the ROC curve. Also, look into and SHAP (Shapley Additive exPlanations), which explains the direction of each variable compared to the outcome variable.
> 

This is a regression problem, so  AUC would not work in this situation. We were using typical regression scoring matrix, such as r^2 and mean absolute error. We will reflect our detailed scoring matrix in the proposal.

> Spelling errors/grammar errors. "Because if the user of our model, accidentally buy a predicted good wine, but actually it is a poor one, the they may lose a lot of money. "

This will be fixed. 

> 
> **5. Exploratory data analysis in a literate code document: VIZ**
> 
> Comments If figure captions are not provided the plot should be clearly explained in the text. I would recommend using figure captions. Missing legends and X and Y axis labels.
> 

This will be fixed.

> **5. Exploratory data analysis in a literate code document: REASONING**
> 
> Comments "After exploring the data distribution for various quality scores, class imbalance could be an issue which require further considerations. As shown in the above table, a vast majority of the sample wines are normal wine; while only a couple of samples are classified as poor or excellent. We may start our model with over- or under-sampling method to balance each class depends on whether it is a vital problem. " What are you going to utilize to fix this?

Class imbalance will be addressed by using Over Sampling technique in our model establishment process. 

Commented from Group 19

**Comment by andytai7** [comment]
Thank you for your hard work.
